### ISSUE TITLE
Contains invalid WIN32 path characters

### ISSUE THREAD

**Issue by flleeppyy** [Anthonyzou/Sourcemap-Unpack#3]
```
D:\development\lastpass>npx source-map-unpacker -p 43819d93/main.43819d93.js.map -o 43819d93/unpacked 
C:\Users\Chen\AppData\Local\npm-cache\_npx\3b29831b4edd3bff\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18
    const errInval = new Error(p + ' contains invalid WIN32 path characters.')
                     ^

Error: D:\development\lastpass\43819d93\unpacked\webpack:\webvault\lp-web-client\packages\assets\svg contains invalid WIN32 path characters.
    at Object.mkdirs (C:\Users\Chen\AppData\Local\npm-cache\_npx\3b29831b4edd3bff\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at Object.mkdirs (C:\Users\Chen\AppData\Local\npm-cache\_npx\3b29831b4edd3bff\node_modules\universalify\index.js:5:67)
    at C:\Users\Chen\AppData\Local\npm-cache\_npx\3b29831b4edd3bff\node_modules\fs-extra\lib\output\index.js:20:11
    at C:\Users\Chen\AppData\Local\npm-cache\_npx\3b29831b4edd3bff\node_modules\universalify\index.js:23:46 {
  code: 'EINVAL'
}
```

**Comment by Anthonyzou** [comment]
Closed by https://github.com/Anthonyzou/Sourcemap-Unpack/commit/efd187cf3fd959240bf8464d69f9f865606937d4
